### ISSUE TITLE
Doc bug

### ISSUE THREAD

**Issue by modernx** [phpnode/YiiRedis#4]
Storing and Retrieving simple keys

Yii::app()->redis->getClient()->set("myKey", "Your Value"); 
echo Yii::app()->redis->getClient->get("myKey"); 
Yii::app()->redis->getClient()->rem("myKey");

right way: getClient(), del

**Comment by vgoodvin** [comment]
Fixed in https://github.com/phpnode/YiiRedis/commit/b15a73e60819122e2ba2b422dc97c6caf3038eb3
