### ISSUE TITLE
flush

### ISSUE THREAD

**Issue by andersonamuller** [phpnode/YiiRedis#7]
In the ARedisCache class, line 118, where is calling:

``` php
return (bool) $this->getConnection()->getClient()->flush();
```

it should call:

``` php
return (bool) $this->getConnection()->getClient()->flushAll();
```

**Comment by vgoodvin** [comment]
Fixed in https://github.com/phpnode/YiiRedis/commit/d3022008b05c27e008891973ba12afacbba138be
